- platform.txt
Fix for https://github.com/arduino/Arduino/issues/7944
Before the upgrade to gcc 5.4, this was treated as a non-fatal warning (when warnings are enabled).  Now some libraries fail to compile.  This simply restores the gcc 4.8 & 4.9 behavior.
> Treat narrowing conversion as warning, not error

- libraries/EEPROM/src/EEPROM.h
> Fix compiler warnings about ignored 'const' in EEPROM.h

- programmers.txt
Use of the `stk500v1` protocol for Arduino as ISP does not work with native USB boards on Windows. The `arduino` protocol does (see https://github.com/arduino/Arduino/issues/1182#issue-9477400).
However, the `arduino` protocol makes it more likely that boards with an external USB interface chip will require the auto-reset circuitry to be disabled to allow them to be used as Arduino as ISP. That adds extra complexity to a process already difficult for the average Arduino user.
For this reason, this pull request does the following:
- Revert the [previous commit changing the Arduino as ISP programmer to use the `arduino` protocol](https://github.com/arduino/ArduinoCore-avr/commit/b084848f2eaf9ccb3ac9a64ac5492d91df4706bf). This restores the Arduino as ISP programmer to maximum compatibility …
> Add ATmega32U4-compatible Arduino as ISP programmer

- cores/arduino/USBAPI.h
- cores/arduino/USBCore.cpp
Based on code originally by Rob van der Veer (from arduino/Arduino#4241), this adds `USBDevice.isSuspended()`, so user sketches can run custom code in their `loop` methods after checking if the device is suspended or not.
This is a port of arduino/Arduino#6964 to `ArduinoCore-avr`. Please let me know if there's anything you want changed, and I'll update the pull request accordingly.
> Add USBDevice.isSuspended()

- cores/arduino/WInterrupts.c
This is just a minor cleanup.
This ISR is currently implemented by the Wire library, on twi.c, and the erased lines are old and dead.
> Remove commented out code for I2C interrupts on WInterrupts.c

- libraries/SoftwareSerial/src/SoftwareSerial.h
Remove `#undef`s in SoftwareSerial.h marked as _Arduino 0012 workaround_ that broke several macros, including `abs`.
Fixes #30.
> Remove historic Arduino 0012 workaround in SoftwareSerial

- cores/arduino/USBCore.cpp
Avoids the unused variable warning if USB is enabled but pluggable USB is not.
> Fix unused variable warning for non-pluggable USB in SendDescriptor

- cores/arduino/Arduino.h
Putting the parameter names in these commonly used prototypes makes syntax help like VS Code's Intellisense work 99% more useful. Without them, it doesn't give you the names of the parameters and you have to remember the semantics yourself. :(
> Add parameter names to common prototypes

- cores/arduino/new.cpp
- cores/arduino/new.h
This adds the missing placement new operator.
The placement new operator is especially useful when working with raw data buffers (often used when implementing data structures to avoid requiring a default constructor).
More information about placement new can be found here:
https://en.cppreference.com/w/cpp/language/new#Placement_new
> Add placement new operator

- cores/arduino/Arduino.h
Currently there are only `bitSet`, `bitClear` and `bitWrite` to write to a bitfield. It is also useful to toggle a bit. Currently toggling would involve a combination of `bitRead` and `bitWrite` but this is not really necessary. Hence my humble submission.
Thank you for Arduino (which I'm using via [KeyboardIO](https://github.com/keyboardio))! 💐
> Add `bitToggle` macro to complement `bitSet` etc

- libraries/Wire/src/utility/twi.c
Added:
` __attribute__ ((fallthrough));`
Reason:
> warning: this statement may fall through [-Wimplicit-fallthrough=]
> [TWI] Add __attribute__ ((fallthrough)) to remove recent GCC warnings

- boards.txt
It is a minor issue but it might cause a problem under the case-sensitive system.
(It seems to be no problem on Windows but not on Linux)
I don't know about the naming convention on the bootloader files, but I try to match with the files in the same directory.
I just fix the path in `boards.txt` rather than rename the file.
> Correct yunmini.bootloader.file on boards.txt

- cores/arduino/WString.cpp
- libraries/SoftwareSerial/src/SoftwareSerial.cpp
Using the current stock `SoftwareSerial` with all warnings enabled results in messages such as the following, observed in a Travis CI build:
```
In file included from /home/travis/.arduino15/packages/arduino/hardware/avr/1.6.23/cores/arduino/Arduino.h:257:0,
from /home/travis/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/SoftwareSerial/src/SoftwareSerial.cpp:43:
/home/travis/.arduino15/packages/arduino/hardware/avr/1.6.23/libraries/SoftwareSerial/src/SoftwareSerial.cpp: In member function 'void SoftwareSerial::begin(long int)':
/home/travis/.arduino15/packages/arduino/hardware/avr/1.6.23/variants/standard/pins_arduino.h:74:39: warning: comparison is always true due to limited range of data type [-Wtype-limits]
#define digitalPinToPCICR(p)    (((p) >= 0 && (p) <= 21) ? (&PCICR) …
```
> Cast pins to signed integers to avoid Wtype-limits compile warning

- cores/arduino/wiring_shift.c
Hi!
I found this -very-little optimization in a function I was using with a 595 shift registers' project: while I was trying to understand what this function used to do, I figured out a (IMHO) cleaner solution.
Compiling an example with `gcc -S` generated a file 10-15 instruction lines shorter than the previous version, which could lead (i think) to a smaller workload for such a simple operation.
I didn't quite understand the double exclamation marks before the shift operation `!!(val & ...` so I don't know if this breaks something. Let me know!
Keep up with Arduino 'cause it's awesome!
> Minor optimization in shiftOut function

- libraries/Wire/examples/i2c_scanner/i2c_scanner.ino
I often use i2c_scanner when I debug circuit.
I'm happy if I can select the project from examples of Arduino IDE.
Could you consider to add this?
Thank you.
Reference: https://playground.arduino.cc/Main/I2cScanner/
> Add i2c_scanner to example of Wire

- platform.txt
Reverts arduino/ArduinoCore-avr#52 .
> Revert "Changed linking order, so precompiled libraries can be used"

- cores/arduino/WInterrupts.c
This commit actually places a copy of your existing code for interrupt handling, but doesn't do the "mix up" you have there for "historic reasons".
The "non-mixup" code is used for the ATmega32u2 and ATmega16u2.
I didn't check every possible interrupt as the board, I'm using, doesn't expose every pin, so please have a short look over the code.
> Interrupt ordering for 32u2 and 16u2 MCU

- cores/arduino/HardwareSerial0.cpp
- cores/arduino/HardwareSerial1.cpp
- cores/arduino/HardwareSerial2.cpp
- cores/arduino/HardwareSerial3.cpp
One character typo in a documentation comment, repeated across a couple files.
Stumbled onto this while browsing the code.
> Fix sine -> since typo in HardwareSerial files

- cores/arduino/new
See discussion in https://github.com/ETLCPP/etl/issues/222#issuecomment-627615713 (breakage of ETL as #include<new> fails).
> Add "new" proxy header for compatibility with c++-standard #include<new>

- cores/arduino/abi.cpp
- cores/arduino/new
- cores/arduino/new.cpp
- cores/arduino/new.h
Since #340, the Arduino core exposes a `new` header (in addition to the previously used `new.h`), but it was incomplete, causing code that previously relied on a more complete `new` header (such as provided by uclibc++) to break. This breakage, and various considerations around improving new/delete were discussed in #287.
This PR fixes this by (almost) completing the `new` header.
This also prepares for letting `new` terminate, rather than returning null on allocation failure. The standard dictates an exception should be thrown, but that is not possible on AVR, so terminating is more similar to raising an exception that is never caught (and thus probably more standards compliant). Code that needs to (portably) handle allocation failure can (after merging this PR) already start using the …
> Improve and complete implementation of new/delete

- cores/arduino/wiring_analog.c
7.3.0-atmel3.6.1-arduino7 gcc fails to optimize separate reading from ADCL and ADCH. It produces additionally three `eor`  commands or in some cases two `mov` commands in the assembly code (see discussion #344). These commands swap register contents before store them to data area. So they are completely unnecessary. Reading ADC result with `ADC` macro fixes it and gcc generates the right code.
> Improve reading ADC result

- boards.txt
- platform.txt
The Google Code URL that was in boards.txt is very outdated.
The URL that was in platform.txt is to a more recent home of the content, which has been replaced with a link to the new location, but while I'm updating boards.txt, I might as well point both URLs to [the real page](https://arduino.github.io/arduino-cli/latest/platform-specification/).
> Update platform specification URLs in configuration files

- libraries/Wire/src/Wire.h
Reverts arduino/ArduinoCore-avr#396
PR was found consuming too much ressources, see [here](https://github.com/arduino/ArduinoCore-avr/pull/396#issuecomment-848204777).
> Revert "Declare TwoWire functions as virtual"

- .codespellrc
The word "statics" was recently added to codespell's "rare" commonly misspelled words directory. By default, this
dictionary is used in addition to the more conservative "clear" dictionary, resulting in a spurious failure of the
"Spell Check" CI workflow.
Although this could be fixed by adding the word to the ignore list, it seems that an increasing number of common words
being added to this dictionary, so I think it's best to just remove it altogether. The goal for the "Spell Check"
workflow is to catch some typos without a significant number of false positives, even if that means some misspellings
slip through. I think the "clear" dictionary is more in line with that goal.
> Don't use codespell's "rare" dictionary for CI spell check

- cores/arduino/CDC.cpp
- cores/arduino/USBCore.cpp
- cores/arduino/USBDesc.h
This change makes it relatively easy to disable the CDC at compiletime.
Disabling it of course means that the serial console won't work anymore, and that you can only flash directly after resetting the board, but I think that's not much of a problem.
`CDC_DISABLED` is also used in ArduinoCore-samd for the same purpose,
see https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/USB/USBDesc.h#L24-L27
Disabling CDC helps making Arduino-based USB devices work with old or otherwise problematic hardware or software.
For example, USB Boot Keyboards don't work with many KVM switches if the CDC sub-devices are there; I'm sure there's other systems with the same problem (BIOS/UEFI implementations? Old operating systems - someone mentioned assistive devices still running Windows XP). …
> Allow disabling CDC with -DCDC_DISABLED

- boards.txt
- platform.txt
- programmers.txt
This PR adds supports for the new upload syntax following the pluggable discovery specification.
> Add support for pluggable discovery

- platform.txt
Network upload on the Arduino Java IDE 1.8.16 is broken since the pluggable upload support addition.
The problem is that, unlike Arduino CLI, the classic Arduino IDE only expands properties with a `tools.TOOL_ID` prefix when running the `tools.TOOL_ID.upload.network_pattern`. Both `TOOL_ID` values must be the same.
This PR fixes the issue.
> Fix legacy `upload.network_pattern` rule

- .github/workflows/compile-platform-examples.yml
The "Compile Examples" GitHub Actions workflow provides a basic "smoke test" for the platform by compiling the relevant example sketches for each of the boards on every commit and pull request.
A new board has been added to the platform ([Uno Mini](https://store.arduino.cc/products/uno-mini-le)) and so should be added to the list of boards compiled for in this workflow.
Even though the Uno compilation does provide reasonable coverage for the Uno Mini due to their similar configurations, that coverage does not extend to [the board definition](https://github.com/arduino/ArduinoCore-avr/blob/1.8.4/boards.txt#L1277-L1306) itself.
> Add unomini to sketch compilation CI workflow

- boards.txt
Arduino has added a new board to the AVR-based line: [the Uno Mini](https://store.arduino.cc/products/uno-mini-le). The Uno Mini has its own board definition in this platform, which produces a dedicated item in the **Tools > Board** menu of the Arduino IDE.
The classic Arduino IDE arranges the Boards menu for each platform according to the order of occurrence of the board definition in the platform's [`boards.txt` configuration file](https://arduino.github.io/arduino-cli/dev/platform-specification/#boardstxt). The previous placement of the Uno Mini board definition resulted in the board appearing at the end of the menu, along with retired and 3rd party boards:
The placement proposed in this PR will cause it to be shown alongside the related [Arduino …
> Use more logical Boards menu placement for Uno Mini

- libraries/Wire/keywords.txt
All the other platform bundled libraries use `KEYWORD1` for the library's global instance so this change provides consistency.
Fixes (in combination with equivalent PRs in the other boards platform repos) https://github.com/arduino/Arduino/issues/8538
> Use established KEYWORD_TOKENTYPE for Wire keyword

- post_install.bat
Otherwise, the driver installation will fail if the current path contains spaces.
It may happen for example if the username has spaces in it: https://github.com/arduino/arduino-cli/issues/1926
> Use correct quoting for paths in post_install.bat

- bootloaders/atmega/ATmegaBOOT_168.c
- bootloaders/atmega8/ATmegaBOOT.c
- bootloaders/bt/ATmegaBOOT_168.c
- bootloaders/caterina-Arduino_Robot/Makefile
- bootloaders/caterina-LilyPadUSB/Makefile
- bootloaders/caterina/Makefile
- bootloaders/gemma/avrdude.conf
- bootloaders/lilypad/src/ATmegaBOOT.c
- bootloaders/stk500v2/Makefile
- cores/arduino/CDC.cpp
- cores/arduino/USBCore.h
- firmwares/atmegaxxu2/arduino-usbdfu/makefile
- firmwares/atmegaxxu2/arduino-usbserial/makefile
This project uses the [**codespell** tool](https://github.com/codespell-project/codespell) to check for commonly misspelled words in the files of the repository.
A recent update to the tool's misspelled words dictionary resulted in the identification of some occurrences of a misspelled word in the comments:
https://github.com/arduino/ArduinoCore-avr/actions/runs/3272628064/jobs/5383865750#step:4:17
```text
Error: ./firmwares/atmegaxxu2/arduino-usbdfu/makefile:[17](https://github.com/arduino/ArduinoCore-avr/actions/runs/3272628064/jobs/5383865750#step:4:18)4: seperated ==> separated
Error: ./firmwares/atmegaxxu2/arduino-usbdfu/makefile:313: seperated ==> separated
Error: ./firmwares/atmegaxxu2/arduino-usbserial/makefile:[19](https://github.com/arduino/ArduinoCore-avr/actions/runs/3272628064 …
```
> Fix misspelled words in comments

- .codespellrc
The [**codespell**](https://github.com/codespell-project/codespell) spellchecker tool is used to automatically detect commonly misspelled words in the files of this project.
The misspelled words dictionary was expanded in the [latest release](https://github.com/codespell-project/codespell/releases/tag/v2.3.0) of codespell. Some of the text in the project codebase happens to match against newly added entries, which caused **codespell** to produce false misspelled word detections.
Since the code that produced the detections is correct and intended, the false positives are resolved by [configuring](https://github.com/codespell-project/codespell#using-a-config-file) **codespell** to ignore the problematic words.
> Fix spell check false positives by ignoring words
